export const FRUIT_AND_VEG_LIST = [
  "lemon",
  "apple",
  "banana",
  "lime",
  "strawberries",
  "orange",
  "pineapple",
  "blueberries",
  "raspberries",
  "coconut",
  "red grapes",
  "green grapes",
  "peach",
  "cherry",
  "kiwis",
  "grapefruit",
  "mandarin oranges",
  "cantaloupe",
  "plum",
  "apricots",
  "fresh figs",
  "raisins",
  "papaya",
  "onion",
  "red onion",
  "green onions",
  "shallot",
  "garlic",
  "tomatoes",
  "lettuce",
  "potatoes",
  "carrots",
  "red chilli",
  "fresh basil",
  "parsley",
  "broccoli",
  "corn",
  "spinach",
  "mushroom",
  "green beans",
  "ginger",
  "celery",
  "cucumber",
  "sweet potato",
  "pickles",
  "avocado",
  "cilantro",
  "olives",
  "asparagus spears",
  "cabbage",
  "cauliflower",
  "dill",
  "kale",
  "pumpkin",
  "squash",
  "fresh mint",
  "eggplant",
  "beets",
  "leeks",
  "brussel sprouts",
  "horseradish",
  "artichokes",
  "bok choy",
  "parsnip",
  "okra",
  "turnips",
  "snow peas",
  "lemongrass"
];

export const MEAT_AND_SEAFOOD_LIST = [
  "ahi tuna",
  "anchovies",
  "bacon",
  "bacon fat",
  "beef",
  "beef brisket",
  "beef chuck roast",
  "beef tenderloin",
  "canned tuna",
  "carp",
  "cat fish filets",
  "chicken bouillon",
  "chicken breasts",
  "chicken broth",
  "chicken drumsticks",
  "chicken legs",
  "chicken pieces",
  "chicken sausage",
  "chicken tenders",
  "chicken thighs",
  "chicken wings",
  "chorizo sausage",
  "clams",
  "cod",
  "crab meat",
  "duck fat",
  "egg",
  "egg white",
  "egg yolk",
  "fish",
  "flank steak",
  "ground beef",
  "ground chicken",
  "ground lamb",
  "ground pork",
  "ground veal",
  "ham",
  "halibut fillet",
  "italian sausages",
  "lamb",
  "lean ground beef",
  "lean ground turkey",
  "lean pork tenderloin",
  "leg of lamb",
  "meat",
  "meatballs",
  "mussels",
  "pancetta",
  "paneer",
  "pepperoni",
  "polish sausage",
  "pork",
  "pork belly",
  "pork chops",
  "pork shoulder",
  "pork tenderloin",
  "proscuitto",
  "raw shrimp",
  "roasted chicken",
  "rotisseri chicken",
  "round steak",
  "salmon fillet",
  "sausage",
  "sirloin steak",
  "turkey",
  "turkey breast"
];

export const DAIRY_LIST = [
  "almond milk",
  "asiago cheese",
  "brie",
  "butter",
  "buttermilk",
  "cheddar",
  "cheese",
  "cheese curds",
  "cheese dip",
  "chocolate milk",
  "chocolate ice cream",
  "coconut milk",
  "colby jack",
  "cotija cheese",
  "cottage cheese",
  "cream",
  "cream cheese",
  "double cream",
  "fontina cheese",
  "fresh mozzarella",
  "goat cheese",
  "gouda cheese",
  "greek yoghurt",
  "gruyere",
  "ice cream",
  "low fat milk",
  "low fat plain yoghurt",
  "low fat sour cream",
  "milk",
  "monterey jack cheese",
  "pecorino",
  "plain greek yoghurt",
  "plain nonfat yoghurt",
  "plain yoghurt",
  "provolone",
  "rice milk",
  "ricotta",
  "salted butter",
  "sharp cheddar cheese",
  "sheeps milk cheese",
  "shredded mozarella",
  "sour cream",
  "white chocolate",
  "yoghurt"
];

export const GRAINS_AND_FLOUR_LIST = [
  "almond flour",
  "angel hair pasta",
  "arborio rice",
  "baguette",
  "basmati rice",
  "bread",
  "bread flour",
  "brown rice",
  "brown rice flour",
  "bulgur",
  "cake flour",
  "cereal",
  "coconut flour",
  "cooked quinoa",
  "cooked wild rice",
  "corn flakes cereal",
  "corn flour",
  "cornstarch",
  "garbanzo bean flour",
  "grain blend",
  "italian bread",
  "jasmine rice",
  "oat flour",
  "oats",
  "pastry flour",
  "potato starch",
  "quinoa",
  "quinoa flour",
  "rice flour",
  "rice noodles",
  "rice paper",
  "rye bread",
  "rye meal",
  "self-rising flour",
  "short grain rice",
  "sourdough bread",
  "spaghetti",
  "spelt flour",
  "steel cut oats",
  "tapioca flour",
  "whole wheat flour",
  "whole wheat bread"
];

export const LIQUIDS_AND_SAUCES_LIST = [
  "sesame oil",
  "olive oil",
  "vegetable oil",
  "coconut oil",
  "peanut oil",
  "sunflower oil",
  "soy milk",
  "beef stock",
  "chicken stock",
  "fish stock",
  "vegetable broth",
  "mayonnaise",
  "ketchup",
  "mustard",
  "vinegar",
  "soy sauce",
  "light soy sauce",
  "balsamic vinegar",
  "worcestershire sauce",
  "hot sauce",
  "bbq sauce",
  "ranch dressing",
  "cider vinegar",
  "rice vinegar",
  "fish sauce",
  "teriyaki sauce",
  "honey mustard",
  "mirin",
  "tomato paste",
  "salsa",
  "gravy",
  "whole cranberry sauce",
  "orange juice",
  "tomato juice",
  "apple juice",
  "ginger ale",
  "white wine",
  "beer",
  "red wine",
  "vodka",
  "whiskey",
  "tequila",
  "sherry",
  "bourbon",
  "gin",
];

export const MISC_LIST = [
  "almond extract",
  "baking bar",
  "baking soda",
  "balsamic glaze",
  "black pepper",
  "brandy",
  "brown sugar",
  "casear dressing",
  "cajun seasoning",
  "caramel sauce",
  "champagne",
  "coffee",
  "kahlua",
  "kosher salt",
  "maple syrup",
  "onion powder",
  "oregano",
  "pesto",
  "red pepper flakes",
  "salt",
  "saffron threads",
  "sage",
  "seasoning",
  "seasame oil",
  "sugar",
  "tahini",
  "vanilla bean",
  "white sugar",
  "white pepper",
  "white vinegar",
  "wine",
  "white bread"
];
